### ISSUE TITLE
使用efi遇到同一报错

### ISSUE THREAD

**Issue by z316174018** [Hush-vv/Lenovo-XiaoXinPro13-Hackintosh#3]
大佬你好，我的机型是pro13 i7 sn730（bios已刷）。我使用你的efi在安装Big Sur beta10以及11.0.1beta均遇到了“disk:device is write locked”的报错，但是在Big Sur最初版本publicbeta并没有问题，想请教一下这个有解决方法没

**Comment by Hush-vv** [comment]
> 大佬你好，我的植入是pro13 i7 sn730（bios已刷）。我使用你的efi在安装Big Sur beta10以及11.0.1beta均遇到了“ disk：device is write lock”的报错，但是在Big Sur最初版本publicbeta并没有问题，想请教一下这个有解决方法没

格式化为apfs

**Comment by z316174018** [comment]
![IMG_6772](https://user-images.githubusercontent.com/61338279/97808059-5f595580-1c9f-11eb-85f5-2f58f73f96be.jpeg)
错误是这个样子的，搜遍全网没有发现解决方法

**Comment by Hush-vv** [comment]
> ![IMG_6772](https://user-images.githubusercontent.com/61338279/97808059-5f595580-1c9f-11eb-85f5-2f58f73f96be.jpeg)
> 错误是这个样子的，搜遍全网没有发现解决方法

我是ota的并没有去测试全新安装，这些应该是系统bug吧

**Comment by holoto** [comment]
> > ![IMG_6772](https://user-images.githubusercontent.com/61338279/97808059-5f595580-1c9f-11eb-85f5-2f58f73f96be.jpeg)
> > 错误是这个样子的，搜遍全网没有发现解决方法
> 
> 我是ota的并没有去测试全新安装，这些应该是系统bug吧

  我也遇到了 我是10.15.7 ota升级的

**Comment by zpengcom** [comment]
> > > ![IMG_6772](https://user-images.githubusercontent.com/61338279/97808059-5f595580-1c9f-11eb-85f5-2f58f73f96be.jpeg)
> > > 错误是这个样子的，搜遍全网没有发现解决方法
> > 
> > 
> > 我是ota的并没有去测试全新安装，这些应该是系统bug吧
> 
>   我也遇到了我是10.15.7 ota升级的

我也是OTA 升级遇到同样的错，打算今晚全新安装

**Comment by Hush-vv** [comment]
> > > > ![IMG_6772](https://user-images.githubusercontent.com/61338279/97808059-5f595580-1c9f-11eb-85f5-2f58f73f96be.jpeg)
> > > > 错误是这个样子的，搜遍全网没有发现解决方法
> > > 
> > > 
> > > 我是ota的并没有去测试全新安装，这些应该是系统bug吧
> > 
> > 
> >   我也遇到了我是10.15.7 ota升级的
> 
> 我也是OTA升级遇到同样的错，打算今晚全新安装

确认已经解锁CFG以及DVMT，尝试AAPL,ig-platform-id=12345678

**Comment by holoto** [comment]
我已经解决了  这个代码报错是正常的
卡住是因为有其他问题
建议大家等5分钟 接下来的代码就是问题

**Comment by litianyangz** [comment]
@holoto 等待五分钟之后 进入安装界面 选不了磁盘

**Comment by litianyangz** [comment]
@holoto 我是OTA升级 安装一会会显示禁止的logo
用U盘重装会出现device is write locked 等五分钟，进入安装界面 没法选磁盘

**Comment by holoto** [comment]
我最终解决这个问题了  是我自己之前添加的一个硬盘驱动补丁 
建议大家把配置文件关于 硬盘驱动的 先暂时关闭
