### ISSUE TITLE
BOIS固件更新失败

### ISSUE THREAD

**Issue by Wilyte** [Hush-vv/Lenovo-XiaoXinPro13-Hackintosh#4]
下载了文中百度网盘的BOIS在Windows 10下更新，重启后提示固件无效。

硬件环境：

小新 pro 13.3 2019
CPU: i7-10710U
网卡: CS2
BIOS: CLCN32WW

PS：Windows 10老死机（在登录界面，输入一两个密码就卡住了），怀疑和CS2网卡相关，不知道怎么解决，如有方案请告知，非常感谢。

**Comment by fanboynet** [comment]
CS2网卡的话，如果win10老死机，建议看下转接卡的11，12针屏蔽了没。不用测试版bios直接用解锁工具就可以了，按教程也很方便。

**Comment by Wilyte** [comment]
> CS2网卡的话，如果win10老死机，建议看下转接卡的11，12针屏蔽了没。不用测试版bios直接用解锁工具就可以了，按教程也很方便。

非常感谢，我试试
