### ISSUE TITLE
电池电量是否显示正确？

### ISSUE THREAD

**Issue by fanboynet** [Hush-vv/Lenovo-XiaoXinPro13-Hackintosh#5]
使用了这边的EFI。发现电池电量显示还是不对，系统是11.1，好像没啥解决办法。像是SMCBatteryManager的问题。

**Comment by Hush-vv** [comment]
> 使用了这边的EFI。发现电池电量显示还是不对，系统是11.1，好像没啥解决办法。像是SMCBatteryManager的问题。

上传图片看看？

**Comment by fanboynet** [comment]
![image](https://user-images.githubusercontent.com/48902228/103253426-129eac00-49bc-11eb-8dc1-050dbe7a7bb6.png)
这个是用充电状态，显示不了充电时长。
用电池后，如图：显示不了剩余时间。
![image](https://user-images.githubusercontent.com/48902228/103253458-4083f080-49bc-11eb-8e65-bb28b09470a9.png)
然后我换用ACPIBatteryManager.kext就可以显示了。用SMCBatteryManager.kext则无法显示。

**Comment by Hush-vv** [comment]
> ![图片](https://user-images.githubusercontent.com/48902228/103253426-129eac00-49bc-11eb-8dc1-050dbe7a7bb6.png)
> 这个是用充电状态，显示不了充电时长。
> 用电池后，如图：显示不了剩余时间。 然后我换用ACPIBatteryManager.kext就可以显示了。用SMCBatteryManager.kext则无法显示。
> ![图片](https://user-images.githubusercontent.com/48902228/103253458-4083f080-49bc-11eb-8e65-bb28b09470a9.png)

今日更新的已经可以正常显示了，可以u盘更新试试
<img width="960" alt="DD2D7EB68E246B7FA8F99C62D3EAD6A8" src="https://user-images.githubusercontent.com/61744850/106983816-7da08700-67a1-11eb-9585-c74fa098f4fd.png">

**Comment by fanboynet** [comment]
你好，电池剩余时间能正常显示了，看你这边好像改了SSDT，感谢。
但是直接用release的config.plist上面有一段使用了**SMCSuperIO.kext**，这个在kext文件夹不存在，启动会报这文件找不到，我这边把这段删除后就正常了。

**Comment by Hush-vv** [comment]
> 你好，电池剩余时间能正常显示了，看你这边好像改了SSDT，感谢。
> 但是直接用release的config.plist上面有一段使用了**SMCSuperIO.kext**，这个在kext文件夹不存在，启动会报这文件找不到，我这边把这段删除后就正常了。

嗯，这个文件忘记放进去了，自己加上去也行的。把这段删除也可以

**Comment by fanboynet** [comment]
> > 你好，电池剩余时间能正常显示了，看你这边好像改了SSDT，感谢。
> > 但是直接用release的config.plist上面有一段使用了**SMCSuperIO.kext**，这个在kext文件夹不存在，启动会报这文件找不到，我这边把这段删除后就正常了。
> 
> 嗯，这个文件忘记放进去了，自己加上去也行的。把这段删除也可以

还有个细节问题，github直接点进去的config.plist里的机型是用MacBookPro16,2，但在USBPorts.kext里还是用的Air。而Release发布的zip里的版本是正确的。

**Comment by Hush-vv** [comment]
> > > 你好，电池剩余时间能正常显示了，看你这边好像改了SSDT，感谢。
> > > 但是直接用release的config.plist上面有一段使用了**SMCSuperIO.kext**，这个在kext文件夹不存在，启动会报这文件找不到，我这边把这段删除后就正常了。
> > 
> > 
> > 嗯，这个文件忘记放进去了，自己加上去也行的。把这段删除也可以
> 
> 还有个细节问题，github直接点进去的config.plist里的机型是用MacBookPro16,2，但在USBPorts.kext里还是用的Air。而Release发布的zip里的版本是正确的。
Release发出之前我还没有更换SMBIOS，发出之后我更换了我的SMBIOS为MacBookPro16,2，它似乎可以更好的性能释放，问题不大，自己更换成自己想用的机型就好

**Comment by Hush-vv** [comment]
Release发出之前我还没有更换SMBIOS，发出之后我更换了我的SMBIOS为MacBookPro16,2，它似乎可以更好的性能释放，问题不大，自己更换成自己想用的机型就好
