### ISSUE TITLE
Great!

### ISSUE THREAD

**Issue by ElwynnLiyoh** [Hush-vv/Lenovo-XiaoXinPro13-Hackintosh#6]
装上了，非常感谢！就是不知道你的网卡怎么装上去的。。。

**Comment by fanboynet** [comment]
如果是原版intel201的网卡，要单独使用驱动：
https://github.com/OpenIntelWireless/itlwm
正常上网是还算是可以用的，某些功能不支持而以。
要完整功能的话，建议更换苹果原装网卡BCM94360CS2

**Comment by ElwynnLiyoh** [comment]
> 如果是原版intel201的网卡，要单独使用驱动：
> https://github.com/OpenIntelWireless/itlwm
> 正常上网是还算是可以用的，某些功能不支持而以。
> 要完整功能的话，建议更换苹果原装网卡BCM94360CS2

嗯，我换dw150了，装上驱动完美！但我的意思是，白果网卡的尺寸，怎么装进机身的。。。螺丝是不用拧了吗hh

**Comment by fanboynet** [comment]
> > 如果是原版intel201的网卡，要单独使用驱动：
> > https://github.com/OpenIntelWireless/itlwm
> > 正常上网是还算是可以用的，某些功能不支持而以。
> > 要完整功能的话，建议更换苹果原装网卡BCM94360CS2
> 
> 嗯，我换dw150了，装上驱动完美！但我的意思是，白果网卡的尺寸，怎么装进机身的。。。螺丝是不用拧了吗hh

是的，CS2的话，要加转接板，并且确实是没办法拧螺丝的。不过后盖盖上，也没多大问题，本身感觉转接板卡得也算牢固的。

**Comment by Hush-vv** [comment]
> 装上了，非常感谢！就是不知道你的网卡怎么装上去的。。。

**Comment by Hush-vv** [comment]
> 装上了，非常感谢！就是不知道你的网卡怎么装上去的。。。

![IMG_4110](https://user-images.githubusercontent.com/61744850/108526157-c44ac100-730b-11eb-8f45-09f25dd508ec.JPG)
![IMG_4111](https://user-images.githubusercontent.com/61744850/108526163-c57bee00-730b-11eb-8288-e91df009ea14.JPG)
